language: cpp

sudo: false

compiler:
- clang
- gcc

os:
- linux
#- osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.9
    - g++-4.9
    - clang
    - cmake
    - cmake-data

before_install:
   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install: 
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make

script: 
  - make test ARGS="-V"
 
#notifications:
#  mail: false
