language: cpp

sudo: false

compiler:
- clang
- gcc

os:
- linux
- osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.9
    - g++-4.9
    - clang

before_install:
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y ; fi
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then sudo apt-get -qq update ; fi
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then sudo apt-get install -qq gcc-4.9 ; fi
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then sudo apt-get install -qq g++-4.9 ; fi
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then export CC=/usr/bin/gcc-4.9 ; fi
#  - if [[ $TRAVIS_OS_NAME == "linux" && "$CXX" == "g++" ]]; then export CXX=/usr/bin/g++-4.9 ; fi
   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

install: 
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make

script: 
  - ./timeit
  - ./main 
 
